import Head from "next/head";
import type { NextPageWithLayout } from "../../_app";
import type { ReactElement } from "react";
import Layout from "../../../layout/Layout";
import LogInPage from "@/views/Login/LoginPage";

const Login = () => {
  return (
    <>
      <Head>
        <title>BOOK ROOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LogInPage />
    </>
  );
};

Login.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Login;
