import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import type { NextPageWithLayout } from "./_app";
import type { ReactElement } from "react";
import Layout from "./../components/layout/Layout";
import Multiselect from "multiselect-react-dropdown";
import { Catalog } from "./catalog.styled";
import { Poppins } from "next/font/google";
import DropDowns from "@/components/UI/dropdown/AllComponentsDropDowns/DropDowns";

const poppins = Poppins({ subsets: ["latin"], weight: "700" });

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>BOOK ROOM</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Catalog>
        <div className="catalog-filter">
          <h1 className={poppins.className}>Catalog</h1>
          <DropDowns />
        </div>
        <div className="catalog-content"></div>
      </Catalog>
    </>
  );
};

Home.getLayout = function getLayout(page: ReactElement) {
  return <Layout>{page}</Layout>;
};

export default Home;
